---
apiVersion: getambassador.io/v2
kind: AmbassadorInstallation
metadata:
  name: ambassador
spec:
  installOSS: true
  helmValues:
    deploymentTool: amb-oper-microk8s
    replicaCount: 1
    deploymentStrategy:
      type: Recreate
    service:
      type: NodePort
      ports:
        - name: http
          port: 80
          hostPort: 80
          targetPort: 8080
          protocol: TCP
        - name: https
          port: 443
          hostPort: 443
          targetPort: 8443
          protocol: TCP
